# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Cadow
email: eric@cadow.net
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Eric Cadow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cadow.net" # the base hostname & protocol for your site
twitter_username: luckycadow
github_username:  luckycadow

# Build settings
markdown: kramdown
sass:
    style: compressed
    sass_dir: _sass
